version: '3.4'

services:
  restapi:
    image: ${DOCKER_REGISTRY-}restapi
    build:
      context: .
      dockerfile: RestApi/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"

  # kotlin-client:
  # #   image: ${DOCKER_REGISTRY-}kotlin-client-1
  #   build:
  #     context: ../Kotlin-Clients/
  #     dockerfile: Dockerfile
  #   deploy:
  #       mode: replicated
  #       replicas: 1
  
  logger:
    image: ${DOCKER_REGISTRY-}logger
    build:
      context: .
      dockerfile: Logger/Dockerfile

  # authenticator:
  #   image: ${DOCKER_REGISTRY-}authenticator
  #   build:
  #     context: .
  #     dockerfile: Authenticator/Dockerfile

  # rabbitmq:
  #   image: 'rabbitmq:3.13-alpine'
  #   ports:
  #     - "5672:5672"
  #   deploy:
  #       mode: replicated
  #       replicas: 1
  #   volumes:
  #     - ./rabbitmq-dataB:/var/lib/rabbitmq/
  
  # aggregator:
  #   image: ${DOCKER_REGISTRY-}aggregator
  #   build:
  #       context: ./Aggregator/
  #       dockerfile: Dockerfile
