apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authenticator-policy
  namespace: default
spec:
    podSelector:
        matchLabels:
        app: authenticator
    policyTypes:
    - Ingress
    ingress:
    - from:
        - podSelector:
            matchLabels:
            app: restapi    